### ISSUE TITLE
Player deaths are double-reported due to direct calls to `EEKilled` game engine event handler method

### ISSUE THREAD

**Issue by tjensen** [ysaroka/InediaInfectedAI#48] opened 2024-10-25 21:59 UTC
When this mod is loaded, player deaths caused by zombie kills are double reported. This is due to the mod's directly calling the `EEKilled` method, which should not be done since it is a game engine event handler method. The `EEKilled` method should only ever be called internally by the game engine.

Other mods that introduce side effects on player deaths via `EEKilled` end up having their side effects doubled by InediaInfectedAI. For example, the [Keep it dead - ProjectBR](https://steamcommunity.com/sharedfiles/filedetails/?id=2608895186) mod, which spawns a "player zombie" when a player dies, ends up spawning **two** player zombies when the player is killed by a zombie due to InediaInfectedAI's improper `EEKilled` calls.

**Comment by ysaroka** [comment] 2024-10-25 22:07
The mod is not supposed to call EEKilled() by design, what’s happening now is the triggering of fallback logic intended for cases when, for some reason, ProcessDirectDamage() fails to kill the player, but the source still exists. The reason this ‘fallback’ is being triggered is that ProcessDirectDamage() doesn’t work within EEHitBy()—meaning it doesn’t deal damage or kill the player.

By the way, this has long been fixed in the experimental version, all the information is available in the #news channel on Discord.

**Closed as completed** 2024-10-27 17:23 UTC
